version: '3'

services:
    live_site:
        build:
            context: .
            tags:
              - 12ul_livesite:latest
        container_name: live_site
        restart: unless-stopped
        env_file: .env
        ports:
            - "4000:80"
